name: TheEndex
version: ${version}
main: org.lokixcz.theendex.Endex
api-version: 1.20
authors:
  - TheLokia
description: Dynamic, demand-driven market with GUI, events, and Vault economy
softdepend:
  - Vault
  - PlaceholderAPI
  - Essentials
  - EssentialsX
  - CMI
  - SimpleEconomy
  - Economy
  - iConomy
  - Fe
  - XConomy
  - PlayerPoints
  - TokenManager
  - CoinsEngine
  - GemsEconomy
  - RoyaleEconomy
  - TheNewEconomy
  - EzEconomy
libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0
  - io.javalin:javalin:5.6.1
  - com.fasterxml.jackson.core:jackson-databind:2.15.2
  - com.fasterxml.jackson.module:jackson-module-kotlin:2.15.2

commands:
  endex:
    description: The Endex main command
    usage: /endex [help|market|version]
    permission: theendex.market
    aliases: [ ex ]
  market:
    description: Shortcut to The Endex market commands
    usage: /market [buy|sell|price|top|invest]
    permission: theendex.market
    aliases: [ shop, m, trade, exchange, bazaar ]

permissions:
  theendex.market:
    default: true
  theendex.buy:
    default: true
  theendex.sell:
    default: true
  theendex.admin:
    default: op
  theendex.invest:
    default: true
  theendex.web:
    default: true
  # Shop editor permissions
  endex.shop.editor:
    description: Allows access to the shop editor GUI
    default: op
  endex.shop.admin:
    description: Allows admin actions in custom shops (shift-click edit)
    default: op
  # Web interface permissions
  endex.web.trade:
    description: Allows trading via web interface
    default: true
  endex.web.admin:
    description: Allows viewing other players holdings via web API
    default: op
  # Crypto addon permissions
  theendex.crypto.info:
    default: true
  theendex.crypto.balance:
    default: true
  theendex.crypto.buy:
    default: true
  theendex.crypto.sell:
    default: true
  theendex.crypto.transfer:
    default: true
  theendex.crypto.shop:
    default: true
  theendex.crypto.admin:
    default: op
